# Sklearn实现高斯混合模型

In [8]:
import numpy as np
import matplotlib.pyplot as plt

### 生成一些数据用来做实验
### 1、生成均值为1.71，标准差为0.056的男生身高数据

In [9]:
np.random.seed(0)

mu_m = 1.71  #期望为
sigma_m = 0.056  #标准差为
num_m = 10000  #个数为10000
rand_data_m = np.random.normal(mu_m, sigma_m, num_m)
y_m = np.ones(num_m)

### 2、生成均值为1.58，标准差为0.051的女生身高数据

In [10]:
np.random.seed(0)

mu_w = 1.58  #期望为
sigma_w = 0.051  #标准差为
num_w = 10000  #个数为10000
rand_data_w = np.random.normal(mu_w, sigma_w, num_w)
y_w = np.zeros(num_m)

### 3、把男生数据和女生数据合在一起

In [11]:
data = np.append(rand_data_m,rand_data_w)
data = data.reshape(-1,1)
y = np.append(y_m,y_w)
print(data)
print(y)

[[1.80878693]
 [1.7324088 ]
 [1.76480933]
 ...
 [1.60636048]
 [1.57832104]
 [1.64620368]]
[1. 1. 1. ... 0. 0. 0.]


In [12]:
from sklearn.mixture import GaussianMixture
g = GaussianMixture(n_components=2, covariance_type='full', tol=1e-6, max_iter=1000)
g.fit(data)
print(u'类别概率:\t', g.weights_[0])
print(u'均值:\n', g.means_, '\n')
print(u'方差:\n', g.covariances_, '\n')

类别概率:	 0.4997126713994801
均值:
 [[1.57895803]
 [1.70899484]] 

方差:
 [[[0.00251689]]

 [[0.00306315]]] 



In [13]:
from sklearn.metrics import accuracy_score
y_hat = g.predict(data)
print(accuracy_score(y,y_hat))

0.8891
